blank_issues_enabled: false
contact_links:
  - name: Sicherheitslücke melden
    url: https://github.com/zap2021/home-assistant-keba-p40/security/advisories/new
    about: Bitte melde Sicherheitslücken vertraulich und nicht in öffentlichen Issues.
